### ISSUE TITLE
Bug: Conversation fetching stopped working for wallet. "No Pre key set"

### ISSUE THREAD

**Issue by gvoltr** [xmtp/xmtp-android#106]
### Describe the bug

I'm trying to call a `conversations.list()` for a wallet that have conversations. This function returns empty list. In logs I'm seeing a bunch of messages `No Pre key set` with tag `CONVERSATIONS`.

Same code, but with different wallet works just fine and conversations are loaded.

### Expected behavior

`conversations.list()` returns the list of conversations for a wallet.

### Steps to reproduce the bug

Unfortunately I don't have exact steps for this issue. 

In our app we have an option to import wallet private keys and sign internally or sign with external wallet (WC).
This wallet worked fine with internal private keys sign.

After some extensive testing with Wallet Connect external signing, and few unsuccessful sign attempts this wallet bugged and stopped fetching conversations. Clearing cache or reinstalling the app doesn't help. This wallet also stopped working in case of private keys import and internal sign (worked before).

Other wallets are working fine with internal sign as before.

**Comment by nplasterer** [comment]
Hey @gvoltr are you still seeing this issue? It sounds like it might be related to environments. If you export keys from the dev environment and accidentally import them into the prod environment you can get into a state where the keys no longer work.
