### ISSUE TITLE
Remove Wallet Connect V1

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-android#121]
Lets upgrade to Wallet Connect V2 in the example

**Comment by Babak-gh** [comment]
# Wallet Connect V2 implementation using WallectConnect Android Core and WalletConnectModal

## XMTP Example app current state
The example app is using a third-party library: [walletconnectkit-android](https://github.com/pink-room/walletconnectkit-android) version 0.3.2, which is based on the WalletConnect protocol v1.

## Possible Wallet Connect V2 implementation:

- **[WalletConnectModal](https://docs.walletconnect.com/advanced/walletconnectmodal/about):**
WalletConnectModal is a simple ui library intended for advanced use cases where users manage connections strings and associated WalletConnect API's themselves.
   - Pros:
      - It is the official WalletConnect UI library.
      - It is easy to implement.
      - Implementing it in the XMTP Example app shows a real-world use case of connecting XMTP-powered applications to one of the most powerful standards.
   - Cons:
      - It is in Alpha
      
 - **[Web3Modal v3](https://docs.walletconnect.com/web3modal/about):** 
 The Web3Modal SDK allows you to easily connect your Web3 dapp with wallets. It provides a simple and intuitive interface for dapps to request actions such as signing transactions and interacting with smart contracts on the blockchain.
Alternatively to Web3Modal you can integrate WalletConnectModal which is intended for advanced use cases where users manage connection strings and associated WalletConnect API's themselves.
    - Pros:
       - Based on WalletConnect [docs](https://docs.walletconnect.com/), it is easier to implement than WalletConnectModal. 
    - Cons:
       - It is also in Alpha
       
- **[Implementing pure WalletConnect v2 Core and Auth API](https://docs.walletconnect.com/api/auth/overview)**
   - Pros:
      - Probably suitable for more advanced use cases.
      - It is in Production.
   - Cons:
      - Too much implementation complexity, which is unnecessary for the XMTP Example app. 
      
- **The newer version of library (2.0.0-alpha03) which is in alpha, supports WalletConnect protocol v2:**
   - Pros:
      - Fewer changes compared to other solutions, as the example app already uses walletconnectkit-android.
      - It completely abstracts the implementation layer of Wallet Connect V2.
   - Cons:
      - It is in Alpha.
      - It is better to use the official WalletConnect V2 library, as third-party libraries may become discontinued, making the example app outdated for XMTP developers.
      
## Proposed Implementation
The proposed implementation, which you can find in this [pull request](https://github.com/xmtp/xmtp-android/pull/134), is based on WalletConnectModal v1.0.0-beta01 and Core SDK v1.24.0.

**Here are some insight in proposed implementation:**
- I used the public WalletConnect protocol relay server (relay.walletconnect.com), which requires a Project ID from [cloud.walletconnect.com](https://cloud.walletconnect.com). The Project ID must be set under the `PROJECT_ID` field in the app's `build.gradle`.
- WalletConnect V2 UI libraries are based on the Android Navigation component, so I added the library and implemented it in `ConnectWalletActivity`.
- I removed the current implementation of `walletconnectkit-android`, which was based on WalletConnect v1.
- I also added Material Design theming to replace the third-party WalletConnect Button.
- The implementation is based on WalletConnect v2 example's best practices.
- The implementation was tested with MetaMask and Trust Wallet.

**Possible issues and further improvements:**
- WalletConnectModal is in alpha, and its public API and associated documentation may still undergo significant and breaking changes.

**Comment by nplasterer** [comment]
@Babak-gh Thanks for the incredibly well thought out and documented decision. I probably would have gone the route of just bumping the latest version of [walletconnectkit-android](https://github.com/pink-room/walletconnectkit-android) since it would likely have the smallest surface area changes. But appreciate your reasoning and thoughts behind going with the more official library. I will look more indepth at your implementation.

I'm curious the need for the  `PROJECT_ID` field as many of the other sdks don't seem to need that. Is that something we can do away with to help simplify the example? Or possibly a test project id? I'd need to get one of these IDs so I can test your PR locally so it's going to require some extra education on my end to figure out how to get one. The cloud link you linked above requires a logging in.

**Comment by Babak-gh** [comment]
> I'm curious the need for the `PROJECT_ID` field as many of the other sdks don't seem to need that. Is that something we can do away with to help simplify the example? Or possibly a test project id? I'd need to get one of these IDs so I can test your PR locally so it's going to require some extra education on my end to figure out how to get one. The cloud link you linked above requires a logging in.

@nplasterer Apparently, using `PROJECT_ID` is a must-have in WalletConnect (WC) version 2. In version 1 of WC, there was another concept called **bridge-server**, which you could self-host or use custom bridge servers that did not need a `PROJECT_ID`. According to this [FAQ](https://docs.walletconnect.com/advanced/faq) from the WalletConnect documentation, bridge-servers are v1 only, and self-hosting relay servers is not an option at this time in v2. Therefore, every WC user should use the official relay server, which is `wss://relay.walletconnect.org`, and obtain a `PROJECT_ID` from WalletConnect.

[Here](https://github.com/pink-room/walletconnectkit-android/tree/v2/sign/sample/dapp) is the documentation for the new version of [walletconnectkit-android](https://github.com/pink-room/walletconnectkit-android), which indicates that they are also going to use the official WalletConnect relay server. It is also necessary to obtain a `PROJECT_ID` from [cloud.walletconnect.com](https://cloud.walletconnect.com/).

**Comment by nplasterer** [comment]
Got it thanks for the explanation and link to docs giving it a spin now.
