### ISSUE TITLE
Deprecate Composite Codec

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-android#154]
https://community.xmtp.org/t/xip-19-deprecate-the-composite-codec/525

Lets remove the composite codec from the supported types.

**Comment by Babak-gh** [comment]
Hi @nplasterer 
I am not sure if [this XIP](https://community.xmtp.org/t/xip-19-deprecate-the-composite-codec/525) has been approved yet, but I deprecated the `CompositeCodec` in this [PR](https://github.com/xmtp/xmtp-android/pull/163). I just wanted to ease your workload a bit while implementing "Group Chat" ;-) . Here are the steps to completely remove the Composite Codec:

1.  Documentation Update: Updating all client SDKs and other XMTP.org documantations.
2. Decide about complete removal version.
3. Communication: Notifying developers about the deprecation through release notes, blog posts and community forum. 
4. Deprecated Class Removal and increase version.

**Comment by nplasterer** [comment]
🙏 Always much appreciated!
